POST http://localhost:3000/user/signup HTTP/1.1
content-type: application/json

{
    "userId": "te111111st",
    "nickName":"test",
    "password":"test"
}

### 

POST http://localhost:3000/user/signin HTTP/1.1
content-type: application/json

{
    "userId": "te111111st",
    "password":"test"
}

###

POST http://localhost:3000/user/signout HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJJZCI6InRlMTExMTExc3QiLCJpYXQiOjE2NTU1MTIxNjEsImV4cCI6MTY1NTUxMzA2MX0.hKbkp8tquoxUmxdLcY1kM7NTsVzy82LNTeGMsJx076A

###

POST http://localhost:3000/user/refresh HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJJZCI6InRlMTExMTExc3QiLCJpYXQiOjE2NTU1MTIyMDAsImV4cCI6MTY1NjExNzAwMH0.9e8K3ssMWuCm33yWz-zkLnoF6-n5CM2jlpjN5v8B-H8